# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161117_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '博客文章', 'verbose_name_plural': '博客文章'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, help_text='用逗号分割多个标签', max_length=200, verbose_name='标签'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
